### ISSUE TITLE
Descargar e instalar las fuentes en Windows

### ISSUE THREAD

**Issue by jersonmartinez** [jersonmartinez/Git-y-GitHub-hacia-una-cultura-DevOps#117]
Hay una serie de fuentes (tipografías) que son las que está usando el documento. 

Es necesario hacer una instalación de las mismas en Windows, debido a que de esta manera, Word reconocerá que existen en el sistema y las usará. Así tendrá el mismo tipo de letra y estaremos sincronizados.

Dejo un enlace donde las puedes descargar, la fuente se llama [Unitext](https://1drv.ms/u/s!AtF6fInCR2ORixCNhTEvqO8cwbvh?e=56TyaC).

## Descargar las fuentes

![Image](https://user-images.githubusercontent.com/7296281/204868321-ca400730-863e-4502-8834-0c602957dae5.png)

## Extraer las fuentes

![Image](https://user-images.githubusercontent.com/7296281/204868523-209f9fc7-2f41-46ea-a9e6-b8f753b6bad4.png)

## Instalar las fuentes

Asegúrese de tener seleccionadas todas las fuentes y luego hace clic derecho, Instalar.

![Image](https://user-images.githubusercontent.com/7296281/204868742-6cfdea36-eba3-475d-ba23-c2f3f1919526.png)

Esto es todo, ya puede abrir el documento de Word que este ya tiene la fuente de "Unitext" seleccionada.

**Comment by cisnerosivania** [comment]
¡Gracias, mi amorcito bello!

**Comment by jersonmartinez** [comment]
Perfecto. Muchas gracias a usted.
